
# This playbook provides a simple way to deploy 
# the laboranalysis web application to a production server

---

# Defines hosts on which this playbook will be Played
- hosts: localhost
# Defines a connection type to hosts which will be provisioned
  connection: local
# Defines whether host parameters will be audited
  gather_facts: yes

# Defines the roles which will be involved into this Play
  roles:
    # Base OS provisioning
    - basedep
    # Deploy our application
    - laboranalysis
    # Deploy docker stuff
    - geerlingguy.docker
