
---

- name: Add an mongo apt signing key
  apt_key:
    url: https://www.mongodb.org/static/pgp/server-4.2.asc
    state: present
  tags:
    - keys
    - repo
    - mongo

- name: Add mongo repository
  copy:
    dest: "/etc/apt/sources.list.d/mongodb-org-4.2.list"
    content: "deb http://repo.mongodb.org/apt/debian stretch/mongodb-org/4.2 main"
  tags:
    - repo
    - mongo

- name: Install Mongodb
  package:
    name: "mongodb-org"
    update_cache: true
    state: "present"
  tags:
    - packages
    - mongo

- name: Create Mongodb data dir
  file:
    path: "{{ mongodb_db_path }}"
    state: directory
    mode: 0755
    owner: mongodb
    group: mongodb
  tags:
    - files
    - mongo

- name: Create Mongodb service file for systemd
  copy:
    src: "mongodb.service"
    dest: "/etc/systemd/system/mongodb.service"
  tags:
    - systemd
    - mongo

- name: Enable Mongodb systemd service
  service:
    name: "mongodb"
    enabled: "yes"
  tags:
    - systemd
    - mongo

- name: Write mongod.conf file
  template:
    src: "mongod.conf.j2"
    dest: "/etc/mongod.conf"
    backup: "yes"
  notify:
    - Restart mongodb
  tags:
    - config
    - mongo
    