
---

- name: Add stretch-backports (testing) repositories
  apt_repository:
    repo: "{{ item }}"
    filename: testing #stretch-backports
    state: present
  loop: "{{ repos }}"
  tags:
    - provisioning
    - repo

- name: Set stable repository as default
  copy:
    src: "all.pin"
    dest: "/etc/apt/preferences.d/all.pin"
  tags:
    - provisioning
    - repo

- name: Install packages
  package:
    name: "{{ packages }}"
    state: latest
    update_cache: true
    default_release: testing #stretch-backports
  register: install
  ignore_errors: True
  tags:
    - provisioning
    - repo
