
---

- name: Add backports repo
  apt_repository:
    repo: "{{ item }}"
    filename: testing #stretch-backports
    state: present
  loop:
    - deb http://deb.debian.org/debian testing main contrib non-free
    - deb-src http://deb.debian.org/debian testing main contrib non-free
  tags:
    - provisioning
    - repo

- name: Install packages
  package:
    name: "{{ packages }}"
    state: latest
    update_cache: true
    default_release: testing #stretch-backports
  register: install
  ignore_errors: True
  tags:
    - provisioning
    - repo
