---
# TODO: Resolve dnspython installation issue !!!

- hosts: localhost
  connection: local
  gather_facts: yes

  roles:
    - basedep
    - mongodep
    - backports
    - pip
    - laboranalysis
    - gunicorn

---